Fix default constructor build issue on macOS
Building ATen on my system (macOS 10.12.6, clang 8.1.0) fails on Scalar 
since 17757d5100f54027391c4009ee44641abe2b7fb8, with the following error:
```
/pytorch/torch/lib/ATen/../ATen/Scalar.h:16:14: error: call to constructor of
      'at::Scalar' is ambiguous
  Scalar() : Scalar(0L) {}
             ^      ~~
```
It's due to the `L` literal not leading to a suitable constructor, as generated by
`AT_FORALL_SCALAR_TYPES`. This change fixes the error.